Структура моего проекта:

getCerts
-src
--main.py
--transliterator.py
--web.py

Я компилирую exe так:

pyinstaller .\main.spec


main.spec:

# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src\\main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='getCerts',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

distpath = 'C:\Git\getCerts\dist'

main.py:

from web import download_file
from web import get_links
import os

certs_dir = os.path.join(os.path.dirname(__file__), 'certs')
if not os.path.exists(certs_dir):
    os.makedirs(certs_dir)


def main():
    url = "http://crl.roskazna.ru/crl/"
    file_links = get_links(url)
    for link in file_links:
        full_url = url + link if not link.startswith("http") else link
        download_file(full_url, certs_dir)


if __name__ == "__main__":
    main()

Ошибка при запуске exe:

C:\Users\Администратор>"C:\Git\getCerts\dist\getCerts.exe"
Traceback (most recent call last):
  File "main.py", line 19, in <module>
  File "main.py", line 15, in main
  File "web.py", line 13, in download_file
  File "transliterator.py", line 7, in transliterate
  File "transliterate\utils.py", line 75, in translit
  File "transliterate\utils.py", line 41, in ensure_autodiscover
  File "transliterate\discover.py", line 26, in autodiscover
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'C:\\Users\\836D~1\\AppData\\Local\\Temp\\_MEI98602\\transliterate\\contrib\\languages'
[12164] Failed to execute script 'main' due to unhandled exception!
